menu:
  归档: /archives
  关于: /about
rss: /atom.xml
description: 我是小明
social:
  github: https://github.com/HyanCat
  weibo: http://weibo.com/liuguangbujiashao
  stack_overflow:
  facebook:
  twitter: https://twitter.com/HyanCat
  google_plus:
  instagram:

page_comment: true
logo: /images/avatar.jpeg
background:
  cover: https://pico.oss-cn-hangzhou.aliyuncs.com/blog/dtwvg.jpeg
  color: cover-disabled

fancybox: true

cloudtie_productkey:

google_analytics:

favicon: /images/cat.png
apple_touch_icon: /images/cat.png
